version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-1: 
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.43.104:9092 # 暴露在外的地址=
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 0
      KAFKA_MESSAGE_MAX_BYTES: 1000000
      # 删除策略
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_RETENTION_CHECK_INTERVAL_MS: 60000
      KAFKA_LOG_CLEANER_ENABLE: "false"
      # 每个topic只会存在一个partitions 和 1个replication
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - /G/tools/Docker/kafka/docker.sock:/var/run/docker.sock
      
  kafka-2: 
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.43.104:9093 # 暴露在外的地址=
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_MESSAGE_MAX_BYTES: 1000000
      # 删除策略
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_RETENTION_CHECK_INTERVAL_MS: 60000
      KAFKA_LOG_CLEANER_ENABLE: "false"
      # 每个topic只会存在一个partitions 和 1个replication
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - /G/tools/Docker/kafka/docker.sock:/var/run/docker.sock
      
  kafka-3: 
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.43.104:9094 # 暴露在外的地址=
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 2
      KAFKA_MESSAGE_MAX_BYTES: 1000000
      # 删除策略
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_RETENTION_CHECK_INTERVAL_MS: 60000
      KAFKA_LOG_CLEANER_ENABLE: "false"
      # 每个topic只会存在一个partitions 和 1个replication
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - /G/tools/Docker/kafka/docker.sock:/var/run/docker.sock
